package com.mesh_microservices.user_service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents the User entity in the application.
 * This model is mapped to the "User" collection in the MongoDB database.
 */
@Document(collection = "User")
public class User {

    /**
     * The unique identifier for the user, automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The full name of the user.
     */
    private String name;

    /**
     * The user's unique email address, used for login and communication.
     */
    private String email;

    /**
     * The user's password for authentication.
     * Note: This should be stored in an encrypted format in a real application.
     */
    private String password;

    /**
     * The role assigned to the user (e.g., "student", "admin").
     */
    private String role;

    /**
     * The academic department the user belongs to.
     */
    private String department;

    /**
     * The current semester of the user, applicable for students.
     */
    private Integer semester;

    /**
     * A list of subjects the user is associated with or enrolled in.
     */
    private List<String> subjects;

    /**
     * The date and time when the user's account was created.
     */
    private LocalDateTime registeredAt;

    // --- Standard Getters and Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Integer getSemester() {
        return semester;
    }

    public void setSemester(Integer semester) {
        this.semester = semester;
    }

    public List<String> getSubjects() {
        return subjects;
    }

    public void setSubjects(List<String> subjects) {
        this.subjects = subjects;
    }

    public LocalDateTime getRegisteredAt() {
        return registeredAt;
    }

    public void setRegisteredAt(LocalDateTime registeredAt) {
        this.registeredAt = registeredAt;
    }
}