# 3. Azure CLI Deployment (FINAL FIX: Use simplified supported syntax)
- task: AzureCLI@2
  displayName: 'Update Azure Container App Image'
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Starting deployment of $(SERVICE_NAME)..."
      
      # FINAL FIX: Use the supported --registry-server flag to tell ACA where to pull from.
      # The authentication is handled automatically by the Service Principal (Azure-ARM-Manual).
      
      az containerapp update \
        --name $(SERVICE_NAME)-app \
        --resource-group $(AZURE_RESOURCE_GROUP) \
        --image $(ACR_NAME).azurecr.io/$(SERVICE_NAME):$(IMAGE_TAG) \
        --registry-server $(ACR_NAME).azurecr.io 
      
      echo "Deployment command sent successfully."