# azure-pipelines.yml for Discovery Server (Corrected)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'Mesh-Microservices/discovery-server/*'
    exclude:
      - 'infrastructure/*'

variables:
  AZURE_RESOURCE_GROUP: 'mesh-project-rg'
  ACR_NAME: 'meshregistry${substr(md5("mesh-project-rg"), 0, 5)}'
  SERVICE_NAME: 'discovery-server'
  IMAGE_TAG: '$(Build.BuildId)'
  DOCKER_REGISTRY_CONNECTION: 'ACR-Connection'
  AZURE_SUBSCRIPTION: 'Azure-Subscription-Connection'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # STEP 1: Explicitly install Java 17 to fix the "release version 21 not supported" error
  - task: JavaToolInstaller@0
    displayName: 'Use Java 17 for Compilation'
    inputs:
      versionSpec: '17' # Ensure Java 17 is used
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'Preinstalled'

  # STEP 2: Build the JAR file
  - task: Maven@3
    displayName: 'Build $(SERVICE_NAME) JAR'
    inputs:
      mavenPomFile: 'Mesh-Microservices/discovery-server/pom.xml'
      goals: 'package'
      # The Java environment is now set by JavaToolInstaller

  # STEP 3: Build and Push the Docker image
  - task: Docker@2
    displayName: 'Build and Push Image to ACR'
    inputs:
      command: 'buildAndPush'
      containerRegistry: '$(DOCKER_REGISTRY_CONNECTION)'
      repository: '$(SERVICE_NAME)'
      dockerfile: 'Mesh-Microservices/discovery-server/Dockerfile'
      tags: |
        $(IMAGE_TAG)
        latest

  # STEP 4: Deploy
  - task: AzureCLI@2
    displayName: 'Update Azure Container App Image'
    inputs:
      azureSubscription: '$(AZURE_SUBSCRIPTION)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # This step updates the ACA - requires the app to exist first
        az containerapp update \
          --name $(SERVICE_NAME)-app \
          --resource-group $(AZURE_RESOURCE_GROUP) \
          --image $(ACR_NAME).azurecr.io/$(SERVICE_NAME):$(IMAGE_TAG) \
          --yes