package com.mesh_microservices.classroom_service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents the main entity for a classroom.
 * <p>
 * This class is mapped to the "classrooms" collection in MongoDB and acts as the
 * root document containing all information about a class, including its students,
 * sections, and assignments.
 */
@Document(collection = "classrooms")
public class Classroom {

    /**
     * The unique identifier for the classroom, generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The name of the classroom (e.g., "Introduction to Cloud Computing").
     */
    private String classroomName;

    /**
     * The subject of the classroom (e.g., "Computer Science").
     */
    private String subject;

    /**
     * A unique, shareable code that students can use to join the classroom.
     */
    private String classroomCode;

    /**
     * The unique ID of the faculty member who owns and manages the classroom.
     */
    private String facultyId;

    /**
     * The name of the faculty member.
     */
    private String facultyName;

    /**
     * A list of unique IDs for all students enrolled in the classroom.
     */
    private List<String> studentIds = new ArrayList<>();

    /**
     * The timestamp when the classroom was created.
     */
    private LocalDateTime createdAt;

    /**
     * An embedded list of sections, which are used to organize course materials.
     */
    private List<Section> sections = new ArrayList<>();

    /**
     * An embedded list of all assignments for this classroom.
     */
    private List<Assignment> assignments = new ArrayList<>();

    // --- Getters and Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getClassroomName() {
        return classroomName;
    }

    public void setClassroomName(String classroomName) {
        this.classroomName = classroomName;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getClassroomCode() {
        return classroomCode;
    }

    public void setClassroomCode(String classroomCode) {
        this.classroomCode = classroomCode;
    }

    public String getFacultyId() {
        return facultyId;
    }

    public void setFacultyId(String facultyId) {
        this.facultyId = facultyId;
    }

    public String getFacultyName() {
        return facultyName;
    }

    public void setFacultyName(String facultyName) {
        this.facultyName = facultyName;
    }

    public List<String> getStudentIds() {
        return studentIds;
    }

    public void setStudentIds(List<String> studentIds) {
        this.studentIds = studentIds;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Section> getSections() {
        return sections;
    }

    public void setSections(List<Section> sections) {
        this.sections = sections;
    }

    public List<Assignment> getAssignments() {
        return assignments;
    }

    public void setAssignments(List<Assignment> assignments) {
        this.assignments = assignments;
    }
}